# Imports and Functions

In [21]:
#Imports
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
import os #for viewing HTML in web browser
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

In [3]:
'''
Function: Create a df
Inputs: filepath
Outputs: df
'''

def create_df(filepath):
    df = pd.read_csv(filepath[0]) #I think the filepath is a tuple? Unsure why

    return df

In [19]:
'''
Function: Convert the df to HTML, then get the full HTML address so 
that you can open it in a browser window and see all the rows and columns easily.
Inputs: df
Outputs: HTML address
'''
def to_html(df):
    df.to_html('df_view.html')
    full_path = os.path.abspath('df_view.html')
    return full_path

# Load data

### *When re-starting to see if new changes work, restart from the cell under this. This loads the file again so that we create the df from scratch, which prevents us from any issues that would have stemmed from the inplace df changes later on*

In [2]:
#Load file
filepath=('/Users/kyli/Desktop/csv_baseline_data_tall_v001.csv',)

In [4]:
df = create_df(filepath)

In [5]:
type(df)

pandas.core.frame.DataFrame

# Clean data

In [6]:
df.head() #Look at head of data

,StudyPart,UniqueMouse,Cohort,InjuredGroup,Treatment,Included,Lights,HourOfDay,CumulativeHour,Day,Paired Hours,DoseMarker,PercentSleep,SleepBout
0,Baseline,C1-01,C1,Sham,vehicle,Included,Off,0.0,1.0,1.0,NaN,0.0,NaN,NaN
1,Baseline,C1-01,C1,Sham,vehicle,Included,Off,1.0,2.0,1.0,NaN,0.0,NaN,NaN
2,Baseline,C1-01,C1,Sham,vehicle,Included,Off,2.0,3.0,1.0,NaN,0.0,NaN,NaN
3,Baseline,C1-01,C1,Sham,vehicle,Included,Off,3.0,4.0,1.0,NaN,0.0,NaN,NaN
4,Baseline,C1-01,C1,Sham,vehicle,Included,Off,4.0,5.0,1.0,4&5,0.0,NaN,NaN

In [7]:
type(df)

pandas.core.frame.DataFrame

In [8]:
#Drop unnecessary columns - StudyPart, Treatment, Included, Paired Hours, DoseMarker, SleepBout
df.drop(['StudyPart', 'Treatment', 'Included', 'Paired Hours', 'DoseMarker', 'SleepBout'], 
                        inplace=True,
                       axis = 1)

In [9]:
type(df)

pandas.core.frame.DataFrame

In [10]:
df.dropna(how='all', inplace=True) #Drop any rows or columns that have all NaNs. There won't be any cols with all NaNs,
#But there will be rows

,UniqueMouse,Cohort,InjuredGroup,Lights,HourOfDay,CumulativeHour,Day,PercentSleep
0,C1-01,C1,Sham,Off,0.0,1.0,1.0,NaN
1,C1-01,C1,Sham,Off,1.0,2.0,1.0,NaN
2,C1-01,C1,Sham,Off,2.0,3.0,1.0,NaN
3,C1-01,C1,Sham,Off,3.0,4.0,1.0,NaN
4,C1-01,C1,Sham,Off,4.0,5.0,1.0,NaN
...,...,...,...,...,...,...,...,...
12388,C8-16,C8,mFPI,Off,4.0,149.0,7.0,NaN
12389,C8-16,C8,mFPI,Off,5.0,150.0,7.0,NaN
12390,C8-16,C8,mFPI,On,6.0,151.0,7.0,NaN
12391,C8-16,C8,mFPI,On,7.0,152.0,7.0,NaN
12392,C8-16,C8,mFPI,On,8.0,153.0,7.0,NaN

In [ ]:
full_path = to_html(df) #Look at the df in a different tab to ensure it looks normal

In [11]:
scaler = MinMaxScaler() #Normalize sleep percentage from 0-1 way easier than the manual way I did it in other code

In [12]:
df.iloc[:, 7] = scaler.fit_transform(df.iloc[:, [7]])
#iloc represens integer-location-based indexing
#Select all rows (:) and PercentSleep column (7)
#Fit_transform calculates mean, std, and then transforms the data to a 0-1 scale
#Assign the new values to the same locations as where the old values were
df

,UniqueMouse,Cohort,InjuredGroup,Lights,HourOfDay,CumulativeHour,Day,PercentSleep
0,C1-01,C1,Sham,Off,0.0,1.0,1.0,NaN
1,C1-01,C1,Sham,Off,1.0,2.0,1.0,NaN
2,C1-01,C1,Sham,Off,2.0,3.0,1.0,NaN
3,C1-01,C1,Sham,Off,3.0,4.0,1.0,NaN
4,C1-01,C1,Sham,Off,4.0,5.0,1.0,NaN
...,...,...,...,...,...,...,...,...
12388,C8-16,C8,mFPI,Off,4.0,149.0,7.0,NaN
12389,C8-16,C8,mFPI,Off,5.0,150.0,7.0,NaN
12390,C8-16,C8,mFPI,On,6.0,151.0,7.0,NaN
12391,C8-16,C8,mFPI,On,7.0,152.0,7.0,NaN
12392,C8-16,C8,mFPI,On,8.0,153.0,7.0,NaN

In [ ]:
#For PCA, I'm gong to also drop injuredgroup, lights

In [20]:
full_path = to_html(df) #Generate link for viewing full df in another browser wi
print(full_path) #Later, figure out how to make a title

/Users/kyli/Documents/GitHub/Sleep-Analysis/df_view.html

In [ ]:
# Reduce to 2 principal components for visualization
pca = PCA(n_components=2)
pca_result = pca.fit_transform(df.iloc[:, 1:])